# Generated by Django 4.2.2 on 2023-06-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(default=None, max_length=10, null=True)),
                ('rating', models.CharField(choices=[('G', 'Rated G'), ('PG', 'Rated Pg'), ('PG-13', 'Rated Pg 13'), ('R', 'Rated R'), ('NC-17', 'Rated Nc 17')], default='G', max_length=20, null=True)),
                ('synopsis', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyed_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviesOrder', to='movies.movie')),
            ],
        ),
    ]
